### ISSUE TITLE
Select options from structure field

### ISSUE THREAD

**Issue by dionysiusmarquis** [getkirby-v2/panel#1009]
Hey,

it would be nice to get select options from any page structure field. Similar to the Tag approach. Like:

```
fields:
  favorite_drink:
    label: Favorite Drink
    type: select 
    options: structure
    structure:
      page: menu
      name: available_drinks
      field: drinkid
```
