### ISSUE TITLE
Change search background color to white

### ISSUE THREAD

**Issue by jenstornell** [getkirby-v2/panel#1014]
Cred to @medienbaecker

I think it looks much more readable with white background. What do you think (animated gif)?

![8e89265d82fb2ff6c3182f249dbcf13d055bd05a](https://cloud.githubusercontent.com/assets/927011/23354196/4c5191ca-fcd0-11e6-9726-be1527903b93.gif)

https://forum.getkirby.com/t/share-your-custom-panel-css/5298/5

```css
.search-input {
  background-color: white;
}
.search:after {
  border-bottom-color: white
}
.search-section li.active a, .search-section li:hover a {
  color: white;
  background-color: rgba(255, 255, 255, .2);
}
```
