### ISSUE TITLE
The html lang attribute is always set to 'en'

### ISSUE THREAD

**Issue by olach** [getkirby-v2/panel#1017]
The Panel always sets the lang attribute of the html tag to `en`:

```html
<html lang="en">
```

I would like this lang attribute to reflect the language set by the logged in author. For example, I have set my preferred language to Swedish. Since all text in the Panel is presented in Swedish for me, the lang attribute should be set to the correct language code:

```html
<html lang="sv_SE">
```

This will open up possibilities to adjust the Panel UI to specific languages using only CSS.

Example:

```css
html[lang^="en"] .flag {
  background-image: url(flag-en.svg);
}

html[lang^="sv"] .flag {
  background-image: url(flag-sv.svg);
}
```
