### ISSUE TITLE
datetime - defaults

### ISSUE THREAD

**Issue by jensfranke** [getkirby-v2/panel#1039]
Based on the documentation (https://getkirby.com/docs/cheatsheet/panel-fields/datetime) the following way should work to set explicit defaults for `date` and `time`: 
```
default:  
    date: now  
    time: 19.30    
```

in version 2.4.1 only the following way works for me:
```
default: now
```

**Comment by texnixe** [comment]
For me, both the version from the docs and the second one work

```
  datetime:
    label: Date & Time
    type: datetime
    date:
      default: 2012-12-12
    time:
      default: 12:12

  datetime:
    type: datetime
    default:
      date: now
      time: 19.30
```

**Comment by jensfranke** [comment]
For me, this version don't work:

```
date:
  label: Date & Time
  type: datetime
  default:
    date: now
    time: 19.30
```

this version works:

```
date:
  label: Date & Time
  type: datetime
  date:
    default: now
  time:
   default: 11:00
```

regarding the last version I think I misunderstood the docs.

**Comment by lukasbestle** [comment]
I think it should be:

```
date:
  label: Date & Time
  type: datetime
  default:
    date: now
    time: 19:30
```

(with a colon instead of a dot)

**Comment by demlak** [comment]
this is also the only version that works for me `default: now`

also "interval" does not work.. and "now" is 2 hours behind current time..

using kirby 2.4.1

**Comment by demlak** [comment]
these two version are working for me.. but not the solution mentioned in the docs:
```
  datetime:
    label:  Date
    type:   datetime
    time:
      interval: 5
      default: now
    date:
      default: now
```

```
  datetime:
    label:  Date
    type:   datetime
    default: now
```

when i want to set interval like this:

```
  datetime:
    label:  Date
    type:   datetime
    interval: 5
    default: now
```

it is ignored =(

and in every solution, time is 2 hours behind current time =(
(systemtime is CEST)

**Comment by demlak** [comment]
these two version are working for me.. but not the solution mentioned in the docs:
```
  datetime:
    label:  Date
    type:   datetime
    time:
      interval: 5
      default: now
    date:
      default: now
```

```
  datetime:
    label:  Date
    type:   datetime
    default: now
```

when i want to set interval like this:

```
  datetime:
    label:  Date
    type:   datetime
    interval: 5
    default: now
```

it is ignored =(

and in every solution, time is 2 hours behind current time =(
(systemtime is CEST)
