### ISSUE TITLE
Remove the page-uri from `title`-fields of files

### ISSUE THREAD

**Issue by wottpal** [getkirby-v2/panel#1089]
I've added the following title-field to my images:

```yaml
files:
  fields:
    title:
      label: Title
      type: text
      required: false
```

And just like for the normal title-field of the page the panel automatically adds the page-uri underneath. Within the file-viewer it's not clickable but it's there and I think it shouldn't. Or do I miss something?

![bildschirmfoto 2017-08-18 um 11 16 44](https://user-images.githubusercontent.com/3930150/29452765-c9cbd160-8407-11e7-8a78-10ec8e620086.png)

Dennis
