### ISSUE TITLE
CURL configuration basic auth

### ISSUE THREAD

**Issue by alexandre-combemorel** [getkirby-v2/panel#1092]
Hi all !

we are actually using kirby behind a a basic auth protection with and .htpassword. 
When we try to use json fetch queries in a select inside of a blueprint like that:
```
myfield:
    label: My Select
    type:  select
    options: url
    url: site/api/types.json
```
the curl function used behind hit 401 response and doesn't allow us to configure the username password necessary to give access to curl.

Do you have any suggestion to make it work, without editing the kirby source code or removing the password on a specific path on the ngnix/apache server?

Thanks in advance !
