### ISSUE TITLE
Not translated default date in alternate language is not set properly on page creation

### ISSUE THREAD

**Issue by LeBenLeBen** [getkirby-v2/panel#1108]
In a multilingual setup, let’s say you have a Blueprint like this:

```
title: Article

fields:
  title:
    label: Title
    type:  title
    required: true

  date:
    label: Date
    type: date
    format: LL
    default: today
    required: true
    translate: false
```

Go to the panel to create a new page **but not in the default website language**. For example if you have English and French and English is the default, be sure to create the page while the panel language is set to French.

Once the page is created (keep the default for the date), go check the article text file. The date value will be:

```
Date: today
```

Where it should be:

```
Date: 2017-10-11
```

If you create the page in the default language, this issue does not happen.
