### ISSUE TITLE
CamelCase not working in Blueprint

### ISSUE THREAD

**Issue by jdd2405** [getkirby-v2/panel#1145]
In my project I built a frontent form, where visitors can add a new entry. 
Those entries should be editable from the backend.

My Blueprint looks like this
```
...
  locations:
    label: Locations
    type: structure
    ...
    fields:
      ...
      ageMin:
        label: Altersuntergrenze
        type: number
      ageMax:
        label: Altersobergrenze
        type: number
      startTime:
        label: Startzeitpunkt
        type: text
      endTime:
        label: Ende
        type: text
      latLng:
        label: Koordinaten (Latitude/Longitude)
        type: text
```

My form in the frontend uses camelCase as well to store values.
To display the values in a Google Map i fetch the values by ther attribute name in camelCase.

But as soon I change a Sturcture Entry in the backend which came in by the form in the frontend, old values are untouched but new values are added with attribute names in lowercase. Changes made this way do not affect the frontend output.

**Example before change (values from frontend form)**

> jsname: Name
> region: "63"
> website: www.example.com
> latLng: 1.11111,2.22222
> ageMin: "16"
> ageMax: "25"
> startTime: 14:00
> endTime: 17:00
> firstname: Bruce
> lastname: Willis
> email: bruce.willis@example.com
> tel: "+41848800800"

**Example after change (values from backend form)**

> jsname: Name
> region: "63"
> website: www.example.com
> latLng: 1.11111,2.22222
> ageMin: "16"
> ageMax: "25"
> startTime: 14:00
> endTime: 17:00
> firstname: Bruce
> lastname: Willis
> email: bruce.willis@example.com
> tel: "+41848800800"
> **agemin: "18"**
> agemax: "25"
> starttime: 14:00
> endtime: 17:00
> latlng: 1.11111,2.22222

The reason is in **panel/app/src/panel/structure.php** where the function **array_change_key_case** is used a few times. 

I don't like to change all my attribute names to lowercase or snake_case since I find this uggly and means a huge effort to change all those code segments where i retreive or store these values.
