### ISSUE TITLE
Validation fails for image fields

### ISSUE THREAD

**Issue by tillprochaska** [getkirby-v2/panel#1156]
I’ve noticed that the validation of image fields fails under certain conditions.

#### Steps to reproduce
Also see the example below.

1. Add a read-only image field to a blueprint
2. Create a page using that blueprint.
3. The bug occurs only if the content text file for that page doesn’t yet have a value (be it an empty value) set for the image field.

#### Current behaviour
The validation for the image field fails, even though it is not a required field.

#### Expected behaviour
The validation should not fail.

#### Example

`site/blueprints/example.yml`
```yaml
title: Example

fields:
  title:
    type: title
    label: Title
  image:
    type: image
    label: Image
    disabled: true
```

`content/example-1/example.txt`
```markdown
Title: Example Page
```
