### ISSUE TITLE
Option text  of select field does not change accordingly if language changes

### ISSUE THREAD

**Issue by RHansmann** [getkirby-v2/panel#163]
If different labels for each language are specified in an option and the language is changed, the option text of a select box does not change accordingly. I would expect, that if any text field changes to the according language, also the option text of a select fields changes accordingly. But it seems, that the option text is always shown in the user language. But it makes more sense to show the option text also in the selected language.

```
    options:
      a: Option 1
        de: Test1DE
        en: Test1EN
```
