### ISSUE TITLE
Title and Slug

### ISSUE THREAD

**Issue by nunocodex** [getkirby-v2/panel#439]
I think the best way for this 2 fields (title only is defined but we can have a slug field for define the folder name):
- Use a slug type field for define the folder name: we can use this a example and show or not show in the panel:

``` yaml
fields:
  slug:
    type: slug
    uses: [field1, field2]
  field1:
    label: Field1
    type: text
  field2:
    label: Field2
    type: text
```

We need to remove the modal window when create new page and follow the blueprint, when you click to save the file is created.

I think this is the best way for use a personal structure and use kirby for other projects instead the simple site builder.
