### ISSUE TITLE
Select default option uses regex for images/files

### ISSUE THREAD

**Issue by adamcbrewer** [getkirby-v2/panel#496]
When specifying a select type for images in a page, specifying the filename + extension works perfect as a default option, but it would be nice to be able to have some regex/pattern matching for filenames or extensions. For example:

``` yaml
feature_image:
  label: Feature Image
  type: select
  options: images
  # this currently works
  default: feature.jpg 
  # this would be nice to have
  default: feature.*
```
