### ISSUE TITLE
Nested structure fields

### ISSUE THREAD

**Issue by samnabi** [getkirby-v2/panel#510]
It would be great to have structure fields within structure fields. Right now I get the following error:

`The field could not be found in /panel/app/controllers/views/editor.php on Line 60`

**Comment by rhawbert** [comment]
+1 on this one. 

I managed to create a nested structure field... but the panel bails out when one tries to add an entry to the second (child) structure field (some fields disappears). 

Also it recorded the whole array like "['field value xyz']" (with the double quotes).

**Comment by malvese** [comment]
The Docs says you can't put a structure inside a structure: "You can define any number of fields and use the same field types listed. The only exception is a structure field nested in a structure field." so it's no surprise it doesn't work ;)
Curious what the use case is?

**Comment by texnixe** [comment]
Also, I wonder how user friendly such a nested structure would be? Maybe there are other (better) ways to structure content, like using subpages for the main structure and then use a structure field inside those subpages?

**Comment by rhawbert** [comment]
Yes... there are several ways to model the content. 
Sometimes new users' naiveté can bring innovation :-)

The use case I needed was like events with complex times/schedules spread through several days... and each day with different timetables. Example:

```
exschedule:
  label: Extended schedule
  type: structure
  fields:

    day:
      label: Day 
      type: structure
      fields: 

        day_entry:
          label: Day entry
          type: date
          format: DD/MM/YYYY

        timetable:
          label: Day's schedule 
          type: structure
          fields: 
            
            activities:
              label: Activities
              type: structure
              fields: 
                
                one_activity:
                  label: Activity description
                  type:  textarea

                begin_time:
                    label: Begin time
                    type: time

                break:
                    label: Coffee break
                    type: time
                    default: 01:00
                    interval: 15

                end_time:
                    label: End time
                    type: time

```

I haven't tested this blueprint's output but I'd like to be able to rearrange the activities inside a given day. 

Maybe reordering the days (since it's a structure field) isn't the best idea.. but if this parent field wasn't a date field but a text one this might be quite useful.

=)
