### ISSUE TITLE
Advanced subpages listing as table feature request

### ISSUE THREAD

**Issue by afbora** [getkirby-v2/panel#529]
![table](https://cloud.githubusercontent.com/assets/3393422/8637598/f0c97dee-28a1-11e5-8ae7-af1a2a7f61aa.jpg)

Sometimes listing subpages on sidebar are difficult to read and find item. But listing as table is more easy reading and managing the items.

**Features in my mind**
1. Enable/disable table listing on blueprint
2. Customizable each fields and action buttons on blueprint
3. Enable sorting field on blueprint
4. When enabled listing table, "Edit Page" link will appear on sidebar
5. Actions: Edit, Delete, Move, Clone, Custom
6. Searching items with input on table ( I forgot to put search bar on screenshot :) )

In fact, i would like Kirby to modular but i guess implementing this feature less complex more than modular structure on core and panel.

Does anyone have disagreed with me? :)
Thanks

**Sample blueprint file**

```
title: Developers
table:
    bordered: true
    striped: true
    onhover: true
    fields:
        first_name:
            label: First
            sort: true
        last_name:
            label: Last
        age:
            label: First
            sort: true
        actions:
            label: Actions
            options:
                edit: Edit
                delete: Delete
                clone: Clone
                move: Move
                custom:
                    label: Custom Action
                    link: http://                   
fields:
    title:
        label: Title
        type:  text
    first_name:
        label: First Name
        type:  text
    last_name:
        label: Last Name
        type:  text
    age:
        label: Age
        type:  text
    birthday:
        label: Birthday
        type:  date
    about:
        label: About
        type:  textarea
```
