### ISSUE TITLE
Drag & Drop file field feature request

### ISSUE THREAD

**Issue by texnixe** [getkirby-v2/panel#581]
Further to this discussion on the forum:https://forum.getkirby.com/t/hierarchical-multi-select-checkboxes-for-taxonomy/2259/14

Would be great to have a file field, into which you can drag and drop one or more files (and which then does not add a Kirbytag, but the filename). Ideally with an option to limit the number of files, the file type and in case of images also set a minimum width.

**Comment by malvese** [comment]
Displaying thumbnails would also be great.

**Comment by jakobploens** [comment]
+1

**Comment by bastianallgeier** [comment]
This is very high on my list!! I will try to come up with something asap.

**Comment by hellodeloo** [comment]
+1

**Comment by BonsaiBit** [comment]
a basic implementation for one image:

```php
<?php
//site/fields/image/image.php
class ImageField extends BaseField
{
    public static $assets = array(
      'js' => array(
        'image.js',
      ),
      'css' => array(
        'image.css',
      ),
    );

    public function __construct()
    {
        $this->type = 'image';
        $this->label = l::get('fields.image.label', 'Bild');
    }

    public function input()
    {
        $base_url = '/content/'.$this->page->diruri().'/';

        $frame = new Brick('div', null, array('class' => 'bb-image_drop_frame', 'data-path' => $base_url));
        $frame->data('field', 'bbKirbyImageDrop');

        if ($this->value()) {
            $img = new Brick('img', null, array('src' => $base_url.$this->value()));
            $frame->append($img);
        }

        $action = new Brick('div', null, array('class' => 'bb-image_drop'));
        $action_text = new Brick('div', l::get('fields.image.drop', 'Bild hier ablegen'), array('class' => 'bb-image_drop_text'));
        $action->append($action_text);
        $frame->append($action);

        $input = new Brick('input', null, array('type' => 'hidden', 'name' => $this->name(), 'value' => $this->value()));
        $frame->append($input);

        return $frame;
    }
}

```

```javascript
//site/fields/image/assets/js/image.js
(function ($) {

	$.fn.bbKirbyImageDrop = function () {

		return this.each(function () {

      var object = $(this);
      var droparea = $('.bb-image_drop', object),
          image = $('img', object),
          input = $('input', object),
          draggable = $('.draggable');

      droparea.droppable({
        hoverClass: 'over',
        accept: draggable,
        drop: function(e, ui) {
          var path = object.data('path');
          var data = ui.draggable.data('text');
          var imgname = data.slice(data.indexOf(':')+2, data.length-1);

          if(image.length >0){
            image.attr('src', path + imgname);
          }else{
            object.prepend('<img src="'+path + imgname+'"/>');
            image = $('img', object);
          }
          input.attr('value', imgname);
        }
      });
		});
	}

})(jQuery);	
```

```css
/*site/fields/image/assets/css/image.css*/
.bb-image_drop_frame{
  border: 2px dashed #ddd;
  background: #fff;
  width: 100%;
  min-height: 5em;
  padding:4px;
}
.bb-image_drop_frame img{
  z-index: 10;
}
.bb-image_drop_frame .bb-image_drop{
  position: absolute;
  top:0;
  left:0;
  height: 100%;
  width: 100%;
  z-index: 11;
}
.bb-image_drop_frame .bb-image_drop.over{
  background: rgba(221,221,221,0.85);
}
.bb-image_drop_frame .bb-image_drop .bb-image_drop_text{
  position: absolute;
  top:50%;
  margin-top:-0.7em;
  width: 100%;
  text-align: center;
  font-size: 1.5em;
  font-weight: bold;
  color: #ddd;
}
.bb-image_drop_frame .bb-image_drop.over .bb-image_drop_text{
  color:#fff;
}
img + .bb-image_drop .bb-image_drop_text{
  text-shadow: 0 -1px 2px #666666, 0 1px 2px #DDDDDD;
  color: #fff!important;
}
```
