### ISSUE TITLE
Allow renaming of visibility toggle on a per blueprint basis

### ISSUE THREAD

**Issue by texnixe** [getkirby-v2/panel#708]
See issue https://github.com/getkirby/panel/issues/706

**Comment by distantnative** [comment]
Syntax suggestion – maybe also including renaming of `Files` and `Pages` in the sidebar?

```
title: Page
labels:
  pages:  Blog Posts
  files  Documents
  visible:  published
  invisible: unpublished
pages: true
files: true
```

Multi-lang:
```
labels:
  pages:  
    en: Blog Posts
    de: Beiträge
```

Thoughts?
