### ISSUE TITLE
Refactor CSS - allow reusing classes

### ISSUE THREAD

**Issue by Pascalmh** [getkirby-v2/panel#709]
Just one example:

``` css
.mainbar .form .buttons {
    position: fixed;
    bottom: 0;
    // ...
}
```

this makes the .buttons class unusable whitein the whole `.mainbar`. Styles can not be reused as there are several of these strict styles applied.

The Idea would be to do this:

Styling the Button

``` css
.mainbar .form .buttons {
    background: #efefef;
    background: -webkit-linear-gradient(bottom, rgba(#efefef, 1), rgba(#efefef, .9) 75%, rgba(#efefef, 0));
    background: -moz-linear-gradient(bottom, rgba(#efefef, 1), rgba(#efefef, .9) 75%, rgba(#efefef, 0));
    background: -ms-linear-gradient(bottom, rgba(#efefef, 1), rgba(#efefef, .9) 75%, rgba(#efefef, 0));
    background: linear-gradient(bottom, rgba(#efefef, 1), rgba(#efefef, .9) 75%, rgba(#efefef, 0));
    margin: 0;
    padding: 1.5em 3em 1.5em;
}
```

Positioning the Button

``` css
.mainbar .form .buttons-saveordiscard {
    position: fixed;
    bottom: 0;
}
```

This way in custom fields / widgets we can reuse the `.buttons` class.
