### ISSUE TITLE
`language` field in blueprint conflicts with panel language switcher on multilang sites

### ISSUE THREAD

**Issue by rasteiner** [getkirby-v2/panel#790]
Not a major issue. But having a `language` field in a blueprint, like this:

``` yaml
   language:
    label: Language
    type: select
    options:
      de: German
      fr: French
      it: Italian
```

Unexpectedly sets that field when I change the language in the panel here: 
![image](https://cloud.githubusercontent.com/assets/6684137/13432635/c7968770-dfce-11e5-99d4-48fa549a63ca.png)

I guess that's because both (the language switcher and my field) are transmitted with the same input name. I suggest changing the language switcher input name to something more unique (like `kcpanellang` or something) to avoid conflicts.

Of course, a simple work-around is to just use another name for the blueprint field (like `lang`)

**Comment by distantnative** [comment]
I cannot reproduce this. My test blueprint:

```
title: Projects
pages:
  template: project
files: false
fields:
  title:
    label: Title
    type:  text
  text:
    label: Text
    type:  textarea
  language:
    label: Language
    type: select
    options:
      de: German
      fr: French
      it: Italian
```

But I still only see the two languages set up in the `config.php` in the language dropdown:
<img width="707" alt="screen shot 2016-03-08 at 15 53 57" src="https://cloud.githubusercontent.com/assets/3788865/13605060/0169fec4-e546-11e5-9bf6-8d78c50e1815.png">
