### ISSUE TITLE
Sorting in panel creates duplicate sorting numbers

### ISSUE THREAD

**Issue by mockturtlesoup** [getkirby-v2/panel#870]
Identical problem to https://github.com/getkirby/panel/issues/620 on a fresh copy of Kirby 2.3.0 (there was a request to open a new isue if the problem occurs on newer versions). 
Both local (Ubuntu) and remote (ngix).

**Comment by acstll** [comment]
I'm experiencing this issue with the latest version `2.5.12`. Any chances of it being ever resolved (now that v3 is out)? Or maybe someone found a workaround?

**Comment by texnixe** [comment]
@acstll Could you please provide more information when exactly this happens? Please provide blueprints, sorting you have applied, number of pages that cause this to happen etc.

**Comment by acstll** [comment]
Sure, here's some information. Just let me know if you need anything else.

This happened on the live environment I while after I updated the site from `2.1.0` to `2.5.12`. That involved changing the blueprints from .php to .yml (basically only removing the '<?php...' bit).

Here are the blueprints:

## projects.yml

```yaml
title: Projects
pages:
  template: project
files: false
fields:
  title:
    label: Title
    type:  text
```

## project.yml

```yaml
title: Project
pages: false
files:
  sortable: true
  fields:
    alt:
      label: Alternate Text
      type: text
      required: true
    caption:
      label: Caption
      type: text
    layout:
      label: Layout
      type: radio
      default: full
      options:
        full: Full
        half: Half
        third: Third
    embed:
      label: Embed HTML
      type: textarea
      buttons: false
      placeholder: '<iframe src="'
fields:
  meta:
    label: Description
    type: text
    help: Brief description of post content, for SEO purposes so not visible
  infoColor:
    label: About color contrast and accessibility
    type: info
    text: >
      Please make sure there's enough contrast between text and background colors, so
      text remains readable and accessible. [Colorable](https://colorable.jxnblk.com/) is
      a great tool to help with that.
  backgroundColor:
    label: Background color
    type: text
    help: 'Any valid CSS syntax: #000000 for HEX or rgb(0, 0, 0) for RGB'
    width: 1/2
  textColor:
    label: Text color
    type: text
    help: 'Any valid CSS syntax: #000000 for HEX or rgb(0, 0, 0) for RGB'
    width: 1/2
  title:
    label: Title
    type:  text
  agency:
    label: Agency
    type: text
    width: 1/2
  client:
    label: Client
    type: text
    width: 1/2
  category:
    label: Category
    type:  checkboxes
    options:
      art-direction: Art Direction
      visual-design: Visual Design
  medium:
    label: Medium
    type: tags
    help: Shows on project page, e.g. Integrated Campaign
  #mediumShort:
  #  label: Medium (short)
  #  type: tags
  #  help: Shows on home page, e.g. Integrated
  catchphrase:
    label: Catchphrase
    type: textarea
    buttons: { }
  text:
    label: Text
    type: textarea
    buttons:
      - bold
      - link
  cover:
    label: Cover image
    type: images
    limit: 1
    help: Used in the homepage
  media:
    label: Media
    type: images
```

## The projects folder messed up

<img width="503" alt="image" src="https://user-images.githubusercontent.com/851105/54950270-327c8280-4f41-11e9-8d16-ab5979f669a3.png">

I tried twice to manually fix the order, update the folder names (uri) to avoid any conflicts but it still happen. When you try sorting them on the panel, you get a flicker and then it gets back to messed up.

Thank you for the quick reply!
