### ISSUE TITLE
Date field ignores placeholder value

### ISSUE THREAD

**Issue by fabianmichael** [getkirby-v2/panel#874]
The date field ignores the placeholder option. This is not a problem, if you chose a date format like `dd/mm/yyyy`. However, on sites with an international group of editors, a format like `dd/mm/yyyy` or similar could be confusing, because for some locales month and day are swapped (e.g. `mm/dd/yyyy`). But the datepicker (Pikaday) also supports the format value `LL`, which gives you a value like »May 1, 2016«.

When the datefield is empty, the placeholder just shows the format (i.e. `LL`):

![bildschirmfoto 2016-06-22 um 10 18 58](https://cloud.githubusercontent.com/assets/395617/16260078/fa231bf0-3865-11e6-85b7-a658b6e1b09b.png)

Field definition in blueprint:

```
  date:
    icon: calendar
    label: Date
    type: date
    format: LL
    placeholder: Select a date…
    default: today
    required: true
```
