### ISSUE TITLE
Quotation marks in text field inside structure are removed.

### ISSUE THREAD

**Issue by LCD344** [getkirby-v2/panel#892]
I'm making a bootstrap carousel with quotes.

In the panel it looks like a structure with a textarea field for the quote and a text field. 

```
label: Success Stories
type:  structure
entry: >
  {{name}}&nbsp;
fields:
  name:
    label: Full Name
    type:  input
  quote:
    label: Quote
    type:  textarea`
```

But when I save a a text between quotation marks, the quotation sometimes marks just disappear - not in all cases, but in some of them. the only one I could say happens regularly is the first entry.

**Comment by texnixe** [comment]
That's probably due to how textarea fields are saved in the content file for a structure field. I'd just save the text without any quotation marks and add them via CSS. That gives you absolute control over how your quotes look and you do not depend on the quotes actually being added to the text.

**Comment by LCD344** [comment]
Yea, I debugged that far... and I found a workaround. but this should still be flagged. In case somebody in the future wants to make something where there are quotation marks only around certain texts...

**Comment by lukasbestle** [comment]
I tracked down where this comes from with the following reduced test case:

```php
$data = [
	[
		'name' => 'Lorem ipsum',
		'quote' => 'Dolor sit amet.'
	],
	[
		'name' => 'Consetetur sadipscing',
		'quote' => '"Elitr sed diam nonumy eirmod."'
	]
];

echo Spyc::YAMLDump($data, false, false, true);
```

It is basically exactly what Kirby does internally, but only using the Spyc YAML library that Kirby uses.

The result is:

```yaml
- 
  name: Lorem ipsum
  quote: Dolor sit amet.
- 
  name: Consetetur sadipscing
  quote: "Elitr sed diam nonumy eirmod."
```

Note the quotes in the result. If we run that through the YAML parser again, we get this:

```text
Array
(
    [0] => Array
        (
            [name] => Lorem ipsum
            [quote] => Dolor sit amet.
        )

    [1] => Array
        (
            [name] => Consetetur sadipscing
            [quote] => Elitr sed diam nonumy eirmod.
        )

)
```

Note that the quotes are missing. The reason is that those quotes have a meaning in YAML as delimiters for string values. I think this is a bug in Spyc, see https://github.com/mustangostang/spyc/issues/53.
